apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: home
  namespace: {{ .Values.deploymentEnvironment }}
spec:
  rules:
    - host: "rancher.localhost"
      http:
        paths:
          - path: "/{{ .Values.deploymentEnvironment }}/home"
            backend:
              serviceName: home
              servicePort: 80

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-22wwq
    field.cattle.io/ingressState: '{"aG9tZS9tYXRzcHJlaW50L3JhbmNoZXIubG9jYWxob3N0Ly9tYXRzcHJlaW50L2hvbWUvODA=":""}'
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":80,"protocol":"HTTP","serviceName":"{{ .Values.buildEnvironment }}:home","ingressName":"{{ .Values.buildEnvironment }}:home","hostname":"{{ .Values.rootUrl }}","path":"/{{ .Values.buildEnvironment }}/home","allNodes":false}]'
  creationTimestamp: "2020-01-25T19:22:16Z"
  generation: 1
  labels:
    cattle.io/creator: norman
  name: home
  namespace: {{ .Values.buildEnvironment }}
  resourceVersion: "8730061"
  selfLink: /apis/extensions/v1beta1/namespaces/{{ .Values.buildEnvironment }}/ingresses/home
  uid: ff207db1-3fa7-11ea-a8f4-025000000001
spec:
  rules:
    - host: {{ .Values.rootUrl }}
      http:
        paths:
          - backend:
              serviceName: home
              servicePort: 80
            path: {{ .Values.buildEnvironment }}/home
      - {}
