# Default values for matsmongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# the volume that will be mounted for all the mats data
# this volume must be shared by the mongo app, the home app, and all the other apps
persistentVolumeClaim: matsdata
# the rancher user id found by examining the cli access key "View API" and finding the value for the "authn.management.cattle.io/token-userId" field
userId: ""
adminMongoPassword: "Adm1n0"
adminMongoUser: "admin"
matsMongoUser: "matsUser"
matsMongoPassword: "mu-2019"
image:
  repository: mongo
  tag: 4.2.0
  pullPolicy: IfNotPresent

