{{- define "common.ingress" -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.global.rootUrl | replace "https://" "" }}
      http:
        paths:
          - path: "/{{ .Release.Namespace }}/{{ .Values.appName }}"
            backend:
              serviceName: {{ .Values.appName }}
              servicePort: 80
{{- end -}}
{{- end -}}