# Default values for matsmongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
persistentVolumeClaim: matsdata
rootUrl: https://rancher.localhost
matsMongoUser: "matsUser"
matsMongoPassword: "mu-2019"
image:
  repository: matsapps/production
  appVersion: 2.4.2
  pullPolicy: IfNotPresent

