apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: precipitationsub24hr
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.rootUrl | replace "https://" "" }}
      http:
        paths:
          - path: "/{{ .Release.Namespace }}/precipitationsub24hr"
            backend:
              serviceName: precipitationsub24hr
              servicePort: 80
