apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-22wwq
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":80,"protocol":"HTTP","serviceName":"{{ .Values.buildEnvironment }}:{{ .Values.appReference }}","ingressName":"{{ .Values.buildEnvironment }}:matsapps-{{ .Values.buildEnvironment }}","hostname":"{{ .Values.rootUrl }}","path":"/{{ .Values.deploymentEnvironment }}/{{ .Values.appReference }}","allNodes":false},{"protocol":"TCP","serviceName":"{{ .Values.deploymentEnvironment }}:{{ .Values.appReference }}-nodeport","allNodes":true}]'
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: "deployment-{{ .Values.deploymentEnvironment }}-{{ .Values.appReference }}"
  name: {{ .Values.appReference }}
  selfLink: "/apis/apps/v1/namespaces/{{ .Values.deploymentEnvironment }}/deployments/{{ .Values.appReference }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: "deployment-{{ .Values.deploymentEnvironment }}-{{ .Values.appReference }}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"{{ .Values.appReference }}-nodeport","kind":"NodePort","name":"80tcp01","protocol":"TCP"}]]'
      labels:
        workload.user.cattle.io/workloadselector: "deployment-{{ .Values.deploymentEnvironment }}-{{ .Values.appReference }}"
    spec:
      containers:
        - env:
            - name: DEPLOYMENT_ENVIRONMENT
              {{- if eq .Values.deploymentEnvironment "matsdev" }}
              value: "development"
              {{- else if eq .Values.deploymentEnvironment "matspreint" }}
              value: "integration"
              {{- else if eq .Values.deploymentEnvironment "matsint" }}
              value: "production"
              {{- else if eq .Values.deploymentEnvironment "matsprod" }}
              value: "production"
              {{- end }}
            - name: GROUP_ORDER
              value: Upper Air,Ceiling and Visibility,Surface,Precipitation,Radar,METexpress
            - name: ROOT_URL
              value: "{{ .Values.rootUrl }}/{{ .Values.deploymentEnvironment }}/{{ .Values.appReference }}"
          {{- if eq .Values.deploymentEnvironment "matsdev" }}
          image: "matsapps/development:{{ .Values.appReference }}-{{ .Values.image.appVersion }}"
          {{- else if eq .Values.deploymentEnvironment "matspreint" }}
          image: "matsapps/integration:{{ .Values.appReference }}-{{ .Values.image.appVersion }}"
          {{- else if eq .Values.deploymentEnvironment "matsint" }}
          image: "matsapps/production:{{ .Values.appReference }}-{{ .Values.image.appVersion }}"
          {{- else if eq .Values.deploymentEnvironment "matsprod" }}
          image: "matsapps/production:{{ .Values.appReference }}-{{ .Values.image.appVersion }}"
          {{- end }}
          imagePullPolicy: Always
          name: {{ .Values.appReference }}
          ports:
            - containerPort: 80
              name: 80tcp01
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /usr/app/settings
              name: settings
              subPath: "{{ .Values.deploymentEnvironment }}/settings"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: settings
          persistentVolumeClaim:
            claimName: matsdata
status: {}
