apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appReference }}
  namespace: {{ .Values.deploymentEnvironment }}
spec:
  rules:
    - host: "rancher.localhost"
      http:
        paths:
          - path: "/{{ .Values.deploymentEnvironment }}/{{ .Values.appReference }}"
            backend:
              serviceName: {{ .Values.appReference }}
              servicePort: 80
