apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-22wwq
    field.cattle.io/ingressState: '{"YWlyY3JhZnQvbWF0c3ByZWludC9yYW5jaGVyLmxvY2FsaG9zdC8vbWF0c3ByZWludC9haXJjcmFmdC84MA==":""}'
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":80,"protocol":"HTTP","serviceName":"matspreint:aircraft","ingressName":"matspreint:aircraft","hostname":"rancher.localhost","path":"/{{ .Values.deploymentEnvironment }}/{{ .Values.appReference }}","allNodes":false}]'
  labels:
    cattle.io/creator: norman
  name: {{ .Values.appReference }}
  namespace: {{ .Values.deploymentEnvironment }}
  selfLink: /apis/extensions/v1beta1/namespaces/{{ .Values.deploymentEnvironment }}/ingresses/{{ .Values.appReference }}
spec:
  rules:
    - host: "rancher.localhost"
      http:
        paths:
          - backend:
              serviceName: {{ .Values.appReference }}
              servicePort: 80
            path: "/{{ .Values.deploymentEnvironment }}/{{ .Values.appReference }}"