apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  myhost:= "rancher.localhost"
  mypath:= "/{{ .Values.deploymentEnvironment }}/{{ .Values.appReference }}"
  myingressName:="matspreint:aircraft"
  annotations:
    field.cattle.io/creatorId: user-22wwq
    field.cattle.io/ingressState: '{"YWlyY3JhZnQvbWF0c3ByZWludC9yYW5jaGVyLmxvY2FsaG9zdC8vbWF0c3ByZWludC9haXJjcmFmdC84MA==":""}'
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":80,"protocol":"HTTP","serviceName":$myingressName,"ingressName":$myingressName,"hostname":$host,"path":$path,"allNodes":false}]'
  labels:
    cattle.io/creator: norman
  name: {{ .Values.appReference }}
  namespace: {{ .Values.deploymentEnvironment }}
  selfLink: /apis/extensions/v1beta1/namespaces/{{ .Values.deploymentEnvironment }}/ingresses/{{ .Values.appReference }}
spec:
  rules:
    - host: $myhost
      http:
        paths:
          - backend:
              serviceName: {{ .Values.appReference }}
              servicePort: 80
            path: $mypath