apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:{{ .Values.deploymentEnvironment }}:home"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: home
  ownerReferences:
    - apiVersion: apps/v1beta2
      controller: true
      kind: deployment
      name: home
      uid: 6f93c01a-30a8-11ea-a8b0-025000000001
  selfLink: /api/v1/namespaces/{{ .Values.deploymentEnvironment }}/services/home
spec:
  ports:
    - name: 80tcp01-home
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: "deployment-{{ .Values.deploymentEnvironment }}-home"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
