apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:{{ .Release.Namespace }}:mongo"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  labels:
    cattle.io/creator: norman
  name: "mongo"
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: mongoport-mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
  sessionAffinity: None
  type: ClusterIP
