apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - name: mongoport-mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
  sessionAffinity: None
  type: ClusterIP
