# Default values for matsmongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
deploymentEnvironment: matsprod
persistentVolumeClaim: matsdata
rootUrl: https://rancher.localhost
image:
  repository: mongo
  tag: 4.2.0
  pullPolicy: IfNotPresent

