apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":{{ .Values.portNumber }},"protocol":"HTTP","serviceName":"{{ .Release.Namespace }}:{{ .Chart.Name }}","ingressName":"{{ .Release.Namespace }}:matsapps-{{ .Release.Namespace }}","hostname":"{{ .Values.rootUrl }}","path":"/{{ .Release.Namespace }}/{{ .Chart.Name }}","allNodes":false},{"protocol":"TCP","serviceName":"{{ .Release.Namespace }}:{{ .Chart.Name }}-nodeport","allNodes":true}]'
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: "deployment-{{ .Release.Namespace }}-{{ .Chart.Name }}"
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  selfLink: "/apis/apps/v1/namespaces/{{ .Release.Namespace }}/deployments/{{ .Chart.Name }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: "deployment-{{ .Release.Namespace }}-{{ .Chart.Name }}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":{{ .Values.portNumber }},"dnsName":"{{ .Chart.Name }}-nodeport","kind":"NodePort","name":"{{ .Values.portNumber }}tcp01","protocol":"TCP"}]]'
      labels:
        workload.user.cattle.io/workloadselector: "deployment-{{ .Release.Namespace }}-{{ .Chart.Name }}"
    spec:
      containers:
        - env:
            - name: MONGO_URL
              value: "mongodb://{{ .Values.global.matsMongoUser }}:{{ .Values.global.matsMongoPassword }}@mongo:27017/{{ .Chart.Name }}?authSource=admin"
            - name: DEPLOYMENT_ENVIRONMENT
              {{- if eq .Release.Namespace "matsdev" }}
              value: "development"
              {{- else if eq .Release.Namespace "matspreint" }}
              value: "integration"
              {{- else if eq .Release.Namespace "matsint" }}
              value: "production"
              {{- else if or (eq .Release.Namespace "matsprod") (eq .Release.Namespace "metexpress") }}
              value: "production"
              {{- end }}
            - name: GROUP_ORDER
              value: Upper Air,Ceiling and Visibility,Surface,Precipitation,Radar,METexpress
            - name: ROOT_URL
              value: "{{ .Values.rootUrl }}/{{ .Release.Namespace }}/{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Chart.Name }}-{{ .Values.image.appVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.portNumber }}
              name: {{ .Values.portNumber }}tcp01
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /usr/app/settings
              name: settings
              subPath: {{ .Release.Namespace }}/settings
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: settings
          persistentVolumeClaim:
            claimName: matsdata
