apiVersion: v2
name: visibility
version: 2.1.0
appVersion: nightly
description: MATS common for a MATS deployment.
keywords:
- mats
icon: file://../common/matsapp.png
dependencies:
  - name: common
    version: 4.3.0
    repository: file://../common
