apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:{{ .Release.Namespace }}:home"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  labels:
    cattle.io/creator: norman
  name: home-nodeport
  namespace: {{ .Release.Namespace }}
  selfLink: /api/v1/namespaces/{{ .Release.Namespace }}/services/home-nodeport
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: 80tcp01
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-{{ .Release.Namespace }}-home
  sessionAffinity: None
  type: NodePort
